version: '3.9'

services:
  db:
    image: postgres:15
    container_name: films_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - ASYNC_DATABASE_URL=${ASYNC_DATABASE_URL}
      - SYNC_DATABASE_URL=${SYNC_DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
  app: